# python-sitecustomize.py
#
# Installed at /usr/local/share/equinor/python/sitecustomize.py by the
# Dockerfile, with `ENV PYTHONPATH=/usr/local/share/equinor/python` so the file
# is on sys.path for every Python invocation -- including processes inside
# `python -m venv` virtual environments, which inherit PYTHONPATH but do not
# inherit the base interpreter's site-packages. Python automatically imports
# `sitecustomize` very early during interpreter startup (before any user code
# or third-party package), which makes it the right place to apply
# process-wide TLS adjustments.
#
# ============================================================================
# WHAT THIS FILE DOES
# ============================================================================
# It patches `ssl.create_default_context` so that the returned SSLContext no
# longer has the OpenSSL flag `VERIFY_X509_STRICT` set. All other defaults
# (CA trust, hostname matching, expiry, signature checks) are left untouched.
#
# ============================================================================
# WHY THIS IS NEEDED
# ============================================================================
# Equinor's corporate network performs SSL inspection: a man-in-the-middle
# proxy terminates the original TLS connection and re-encrypts it with a
# certificate it generates on the fly, signed by an Equinor internal CA.
# (The Equinor CAs themselves are added to the system and certifi trust
# stores at image build time and post-create time.)
#
# These on-the-fly proxy-generated certificates are missing the
# X.509 "Authority Key Identifier" (AKI) extension. AKI identifies which
# CA key signed the certificate; RFC 5280 says it MUST be present on CA
# certs and SHOULD be present on end-entity certs.
#
# Starting with OpenSSL 3.x (used by Python 3.12+), `create_default_context`
# enables `VERIFY_X509_STRICT`, which causes verification to fail with:
#
#     ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]
#     certificate verify failed: Missing Authority Key Identifier
#
# even though the CA is trusted and the chain is otherwise valid. This
# breaks every Python HTTPS client (requests, httpx, urllib, pip, poetry,
# aiohttp, ...) when used behind the Equinor proxy.
#
# The most surgical fix is to clear the strict flag while preserving all
# other security checks. The alternative — getting the proxy team to issue
# replacement certificates with proper AKI — is outside our control and
# may take an unbounded amount of time.
#
# ============================================================================
# CONSEQUENCES / TRADE-OFFS
# ============================================================================
# Disabling VERIFY_X509_STRICT loses these defense-in-depth checks:
#   * Missing AKI extension                              (tolerated now)
#   * Missing Subject Key Identifier on intermediate CAs (tolerated now)
#   * Non-DER-canonical fields in some legacy encodings  (tolerated now)
#
# What is NOT affected (still strictly enforced):
#   * The full certificate chain must validate to a trusted root
#   * Hostname must match the certificate's CN/SAN
#   * Certificate must be within its validity period
#   * Signatures must verify
#   * Key usage / extended key usage flags are still respected
#
# Effective security model: equivalent to Python 3.11 / OpenSSL 1.1.x defaults.
# Acceptable trade-off given that the only certs we expect to lack AKI are
# generated by an Equinor-internal proxy whose CA we trust by policy.
#
# Scope of the patch:
#   * Only affects `ssl.create_default_context()`. Code that explicitly
#     constructs its own `ssl.SSLContext(...)` and configures verify_flags
#     manually is not influenced (rare in practice).
#   * Process-wide for any Python invocation in this image (sitecustomize is
#     imported before user code).
#   * No effect on Codespaces — Codespaces runs on GitHub infrastructure
#     without SSL inspection, so the strict flag would not cause failures
#     there. The patch is harmless in that case.
#
# Source of the broader CA / proxy story:
#   https://github.com/equinor/proxy-settings
import ssl as _ssl

if hasattr(_ssl, "VERIFY_X509_STRICT"):
    _STRICT = _ssl.VERIFY_X509_STRICT

    # Patch ssl.create_default_context — used by stdlib clients (smtplib,
    # ftplib, simple urllib calls without an explicit context, etc.).
    _orig_create_default_context = _ssl.create_default_context

    def _create_default_context(*args, **kwargs):
        ctx = _orig_create_default_context(*args, **kwargs)
        ctx.verify_flags &= ~_STRICT
        return ctx

    _ssl.create_default_context = _create_default_context
    del _create_default_context

    # Patch ssl.SSLContext.__new__ — used by libraries that build their own
    # context (urllib3 / requests / httpx all do this via
    # `SSLContext(PROTOCOL_TLS_CLIENT)` rather than create_default_context).
    # In Python 3.12+ the SSLContext constructor enables VERIFY_X509_STRICT
    # on its own X509 store, so the create_default_context patch alone is
    # not sufficient for these consumers.
    _orig_new = _ssl.SSLContext.__new__

    def _new(cls, *args, **kwargs):
        ctx = _orig_new(cls, *args, **kwargs)
        try:
            ctx.verify_flags &= ~_STRICT
        except Exception:
            pass
        return ctx

    _ssl.SSLContext.__new__ = staticmethod(_new)
    del _new

    # Override the public name so that downstream code which explicitly
    # re-enables the flag has no effect. urllib3 2.x's
    # `create_urllib3_context` does:
    #
    #     context.verify_flags |= ssl.VERIFY_X509_PARTIAL_CHAIN | ssl.VERIFY_X509_STRICT
    #
    # which would otherwise put the bit straight back. With the constant set
    # to 0, that OR becomes a no-op. The underlying C-level OpenSSL constant
    # is unaffected; only Python-level lookups by name resolve to 0.
    _ssl.VERIFY_X509_STRICT = 0
